import { useState } from 'react';
import { useAdminInvoices } from '../../hooks/useInvoices';
import { PageTitle } from '../../components/shared/PageTitle';
import { formatKES, formatNairobiDate } from '../../lib/utils';
import { Button } from '../../components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '../../components/ui/table';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '../../components/ui/dialog';
import { Loader2, Eye, Download, Receipt, ExternalLink } from 'lucide-react';
import { Invoice } from '../../types/invoices';
import { api } from '../../lib/api';
import { toast } from 'sonner';

const parseQrData = (qrData: string | null) => {
  if (!qrData) return { qrUrl: '', kraSign: '' };
  if (qrData.includes('|')) {
    const parts = qrData.split('|');
    return { kraSign: parts[0], qrUrl: parts[1] };
  }
  return { qrUrl: qrData, kraSign: '' };
};

const handleDownload = async (pdfUrl: string | null, invoiceNumber: string | number) => {
  if (!pdfUrl) return;
  try {
    const response = await api.get(pdfUrl, {
      responseType: 'blob',
    });
    const blob = new Blob([response.data], { type: 'application/pdf' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `invoice_${invoiceNumber}.pdf`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  } catch (error) {
    toast.error("Failed to download invoice PDF.");
  }
};

export default function InvoicesPage() {
  const { data: invoices, isLoading } = useAdminInvoices();
  const [selectedInvoice, setSelectedInvoice] = useState<Invoice | null>(null);

  return (
    <div className="space-y-6">
      <PageTitle title="Invoices | Admin" />

      <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
        <div>
          <h2 className="text-2xl font-bold tracking-tight">Billing & Invoices</h2>
          <p className="text-muted-foreground">View customer invoices and KRA eTIMS receipts.</p>
        </div>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="text-lg">Generated Invoices</CardTitle>
          <CardDescription>History of all invoices generated by successful payments.</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="rounded-md border overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Invoice #</TableHead>
                  <TableHead>Payment ID</TableHead>
                  <TableHead>Amount</TableHead>
                  <TableHead>Date</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {isLoading ? (
                  <TableRow>
                    <TableCell colSpan={5} className="text-center py-8">
                      <Loader2 className="mx-auto h-6 w-6 animate-spin text-muted-foreground" />
                    </TableCell>
                  </TableRow>
                ) : !invoices || invoices.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={5} className="text-center py-8 text-muted-foreground">
                      No invoices found.
                    </TableCell>
                  </TableRow>
                ) : (
                  invoices.map((invoice) => (
                    <TableRow key={invoice.id}>
                      <TableCell className="font-mono text-sm">{invoice.invoice_number}</TableCell>
                      <TableCell className="font-mono text-xs text-muted-foreground">{invoice.payment_id.substring(0, 8)}...</TableCell>
                      <TableCell className="font-semibold text-primary">{formatKES(invoice.amount_kes)}</TableCell>
                      <TableCell className="text-muted-foreground whitespace-nowrap">
                        {formatNairobiDate(invoice.created_at)}
                      </TableCell>
                      <TableCell className="text-right">
                        <Button 
                          variant="ghost" 
                          size="sm" 
                          onClick={() => setSelectedInvoice(invoice)}
                        >
                          <Eye className="h-4 w-4 mr-2" /> View
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>

      <Dialog open={!!selectedInvoice} onOpenChange={(open) => !open && setSelectedInvoice(null)}>
        <DialogContent className="sm:max-w-[425px]">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Receipt className="h-5 w-5" />
              Invoice {selectedInvoice?.invoice_number ? `INV-${selectedInvoice.invoice_number}` : ''}
            </DialogTitle>
            <DialogDescription>
              Amount: <strong className="text-foreground">{selectedInvoice && formatKES(selectedInvoice.amount_kes)}</strong>
            </DialogDescription>
          </DialogHeader>
          
          {selectedInvoice && (() => {
            const { qrUrl, kraSign } = parseQrData(selectedInvoice.kra_etims_qr_code);
            return (
              <div className="space-y-6 py-4 flex flex-col items-center justify-center">
                <div className="space-y-2 text-center w-full flex flex-col items-center">
                  <p className="text-sm font-medium">KRA eTIMS Verification</p>
                  
                  {qrUrl ? (
                    <div className="flex flex-col items-center gap-3">
                      <div className="border p-2 rounded-lg bg-white inline-block shadow-sm">
                        <img 
                          src={`https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(qrUrl)}`}
                          alt="KRA eTIMS QR Code" 
                          className="w-44 h-44 object-contain"
                        />
                      </div>
                      {kraSign && (
                        <p className="text-[10px] font-mono text-muted-foreground max-w-[280px] break-all border bg-muted/30 p-2 rounded text-center">
                          <strong>Signature:</strong><br />
                          {kraSign}
                        </p>
                      )}
                      <a 
                        href={qrUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-xs text-primary hover:underline font-semibold flex items-center gap-1.5"
                      >
                        Verify on KRA Portal <ExternalLink className="h-3.5 w-3.5" />
                      </a>
                    </div>
                  ) : (
                    <div className="border p-4 rounded-lg bg-muted/30 text-muted-foreground text-xs max-w-[280px]">
                      KRA eTIMS Sync Pending or Offline.
                    </div>
                  )}
                </div>
                
                <Button 
                  className="w-full h-10 text-xs font-semibold"
                  disabled={!selectedInvoice.pdf_url}
                  onClick={() => handleDownload(selectedInvoice.pdf_url, selectedInvoice.invoice_number)}
                >
                  <Download className="mr-2 h-4 w-4" /> Download PDF Receipt
                </Button>
              </div>
            );
          })()}
        </DialogContent>
      </Dialog>
    </div>
  );
}
